export const TOOL_ORDER: string[] = [
  "roblox-launcher",
  "automatic-login",
  "launch-emulators",
  "quick-swap-executor-keys",
  "file-management",
  "resource-monitor",
  "cookie-extractor",
  "cookie-checker",
  "close-roblox",
  "close-emulators",
  "arrange-windows",
  "optimize-devices",
  "mass-install-apk",
  "clone-vm",
  "delete-roblox-config",
  "delete-backups",
];
